// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace TerraPlay
{
public static class GPGSIds
{
        public const string achievement_challenge_seeker = "CgkI4LDA_-MGEAIQBQ"; // <GPGSID>
        public const string achievement_sharing_is_caring = "CgkI4LDA_-MGEAIQBA"; // <GPGSID>
        public const string achievement_bad_luck = "CgkI4LDA_-MGEAIQAg"; // <GPGSID>
        public const string leaderboard_terrasweeper_leaderboard = "CgkI4LDA_-MGEAIQBg"; // <GPGSID>
        public const string package_name = "com.ViralGames.TerraSweeper"; // <GPGSID>
        public const string achievement_welcome_to_terrasweeper = "CgkI4LDA_-MGEAIQAw"; // <GPGSID>
        public const string achievement_just_in_time = "CgkI4LDA_-MGEAIQAQ"; // <GPGSID>
        public const string achievement_working_memory = "CgkI4LDA_-MGEAIQCA"; // <GPGSID>

}
}
